{"name": "Calculate", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'wait'\n", "trace": "  File \"C:\\Users\\3last\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\3last\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\steps.py\", line 15, in step_impl\n    context.wait.until(EC.element_to_be_clickable(By.ID, \"sfAgreeAllButton\")).click()\n    ^^^^^^^^^^^^\n  File \"C:\\Users\\3last\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "steps": [{"name": "Given I am situated on the calculator subpage", "status": "passed", "start": 1742124111852, "stop": 1742124111875}, {"name": "When I click calculate button", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'wait'\n", "trace": "  File \"C:\\Users\\3last\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\3last\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\steps.py\", line 15, in step_impl\n    context.wait.until(EC.element_to_be_clickable(By.ID, \"sfAgreeAllButton\")).click()\n    ^^^^^^^^^^^^\n  File \"C:\\Users\\3last\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "start": 1742124111875, "stop": 1742124111875}, {"name": "Then I proceed to credentials page", "status": "skipped", "start": 1742124111875, "stop": 1742124111875}], "start": 1742124111852, "stop": 1742124111875, "uuid": "05199a2b-de59-4ca6-897b-6aec1692cf12", "historyId": "ee488e1c37084f143b18d29742589363", "fullName": "Calculate_default: Calculate", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Calculate_default"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}